open = "2H"
meaning = "Both majors (4-4+)"
notes = ["4-10pts", "(if 4-4 7-10pts;", "If 5-4/4-5 5-10pts", "If 5-5 4-9pts)", "(will not be 4432)", "(* IN 4th POSITION", "Shows 6 hearts", "8-12pts)"]
fourth = "4TH POSITION: 2H shows 6 hearts 8-12pts – for sequences see 2S opening"

[pass.2NT]
meaning = "shape asking"

[pass.2NT.pass.3C]
meaning = "either 4-4 in majors (4441/4414/4450/4405)"
notes = ["7-10pts or minimum, 4-6pts 5-5 in majors"]

[pass.2NT.pass.3C.pass.3D]
meaning = "asking for minor (assuming 4-4)"
rebid = "3H=C; 3S=D; 3NT=5-5"

[pass.2NT.pass.3C.pass."3H/3S"]
meaning = "invitational"
rebid = "Natural"

[pass.2NT.pass.3C.pass."3NT/4H/4S"]
meaning = "to play"

[pass.2NT.pass.3C.pass.4C]
meaning = "slam try in hearts"
rebid = "4D-interest; 4H-min"

[pass.2NT.pass.3C.pass.4D]
meaning = "slam try in spades"
rebid = "4H-interest; 4S-min"

[pass.2NT.pass.3D]
meaning = "minimum (5-7pts) with 5H and 4S"

[pass.2NT.pass.3D.pass."3H/3S"]
meaning = "to play"

[pass.2NT.pass.3D.pass."3NT/4H/4S"]
meaning = "to play"

[pass.2NT.pass.3D.pass.4C]
meaning = "slam try in hearts"
rebid = "4D-interest; 4H-min"

[pass.2NT.pass.3D.pass.4D]
meaning = "slam try in spades"
rebid = "4H-interest; 4S-min"

[pass.2NT.pass.3H]
meaning = "minimum (5-7pts) with 5S and 4H"

[pass.2NT.pass.3H.pass."(pass)/3S"]
meaning = "to play"

[pass.2NT.pass.3H.pass."3NT/4H/4S"]
meaning = "to play"

[pass.2NT.pass.3H.pass.4C]
meaning = "slam try in hearts"
rebid = "4D-interest; 4H-min"

[pass.2NT.pass.3H.pass.4D]
meaning = "slam try in spades"
rebid = "4H-interest; 4S-min"

[pass.2NT.pass.3NT]
meaning = "maximum (8-10pts) with 5S and 4H"

[pass.2NT.pass.3NT.pass.4C]
meaning = "slam try in hearts"
rebid = "4D-interest; 4H-min"

[pass.2NT.pass.3NT.pass.4D]
meaning = "slam try in spades"
rebid = "4H-interest; 4S-min"

[pass.2NT.pass.3NT.pass."4H/4S"]
meaning = "to play"

[pass.2NT.pass.3S]
meaning = "maximum (8-10pts) with 5H and 4S"

[pass.2NT.pass.3S.pass."3NT/4H/4S"]
meaning = "to play"

[pass.2NT.pass.3S.pass.4C]
meaning = "slam try in hearts"
rebid = "4D-interest; 4H-min"

[pass.2NT.pass.3S.pass.4D]
meaning = "slam try in spades"
rebid = "4H-interest; 4S-min"

[pass.2NT.pass."4C/4D"]
meaning = "maximum (7-9pts) 5-5 short in bid m"
rebid = "natural"

[pass.2S]
meaning = "Preference"
rebid = "Opener always passes"

[pass.3C]
meaning = "natural, good suit"

[pass.3C.pass.3D]
meaning = "fit, maximum (likely shortage)"
rebid = "cue bids"

[pass.3C.pass."3H/3S"]
meaning = "5 card suit, no fit minimum"
rebid = "natural"

[pass.3C.pass.3NT]
meaning = "no fit, maximum"
rebid = "natural"

[pass.3C.pass.4C]
meaning = "fit, minimum"
rebid = "cue bids"

[pass.3D]
meaning = "natural, good suit"
rebid = "sequences same as after 2H-3C;"

[pass.3D.pass."3H/3S"]
meaning = "5 card suit, no fit minimum"
rebid = "natural"

[pass.3D.pass.3NT]
meaning = "no fit, maximum"
rebid = "natural"

[pass.3D.pass.4C]
meaning = "fit, maximum (likely shortage)"
rebid = "cue bids"

[pass.3D.pass.4D]
meaning = "fit, minimum"
rebid = "cue bids"

[pass."3H/3S"]
meaning = "mildly invitational"
rebid = "opener should only bid on if max AND distributional"

[pass."3NT/4H/4S"]
meaning = "to play"

[pass.4C]
meaning = "Slam try (hearts)"

[pass.4C.pass.4D]
meaning = "confirms interest"
rebid = "cue bids"

[pass.4C.pass.4H]
meaning = "minimum, little slam interest"

[pass.4D]
meaning = "Slam try (spades)"

[pass.4D.pass.4H]
meaning = "confirms interest"
rebid = "cue bids"

[pass.4D.pass.4S]
meaning = "minimum, little slam interest"
